// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             (unknown)
// source: api/v1/eventstore.proto

package flipbookv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// EventStoreClient is the client API for EventStore service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EventStoreClient interface {
	Append(ctx context.Context, in *Event_AppendRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	Iterate(ctx context.Context, opts ...grpc.CallOption) (EventStore_IterateClient, error)
	GetLatest(ctx context.Context, in *Event_GetLatestRequest, opts ...grpc.CallOption) (*Event, error)
}

type eventStoreClient struct {
	cc grpc.ClientConnInterface
}

func NewEventStoreClient(cc grpc.ClientConnInterface) EventStoreClient {
	return &eventStoreClient{cc}
}

func (c *eventStoreClient) Append(ctx context.Context, in *Event_AppendRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/flipbook.v1.EventStore/Append", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventStoreClient) Iterate(ctx context.Context, opts ...grpc.CallOption) (EventStore_IterateClient, error) {
	stream, err := c.cc.NewStream(ctx, &EventStore_ServiceDesc.Streams[0], "/flipbook.v1.EventStore/Iterate", opts...)
	if err != nil {
		return nil, err
	}
	x := &eventStoreIterateClient{stream}
	return x, nil
}

type EventStore_IterateClient interface {
	Send(*Event_IterateRequest) error
	Recv() (*Event, error)
	grpc.ClientStream
}

type eventStoreIterateClient struct {
	grpc.ClientStream
}

func (x *eventStoreIterateClient) Send(m *Event_IterateRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *eventStoreIterateClient) Recv() (*Event, error) {
	m := new(Event)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *eventStoreClient) GetLatest(ctx context.Context, in *Event_GetLatestRequest, opts ...grpc.CallOption) (*Event, error) {
	out := new(Event)
	err := c.cc.Invoke(ctx, "/flipbook.v1.EventStore/GetLatest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EventStoreServer is the server API for EventStore service.
// All implementations must embed UnimplementedEventStoreServer
// for forward compatibility
type EventStoreServer interface {
	Append(context.Context, *Event_AppendRequest) (*emptypb.Empty, error)
	Iterate(EventStore_IterateServer) error
	GetLatest(context.Context, *Event_GetLatestRequest) (*Event, error)
	mustEmbedUnimplementedEventStoreServer()
}

// UnimplementedEventStoreServer must be embedded to have forward compatible implementations.
type UnimplementedEventStoreServer struct {
}

func (UnimplementedEventStoreServer) Append(context.Context, *Event_AppendRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Append not implemented")
}
func (UnimplementedEventStoreServer) Iterate(EventStore_IterateServer) error {
	return status.Errorf(codes.Unimplemented, "method Iterate not implemented")
}
func (UnimplementedEventStoreServer) GetLatest(context.Context, *Event_GetLatestRequest) (*Event, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLatest not implemented")
}
func (UnimplementedEventStoreServer) mustEmbedUnimplementedEventStoreServer() {}

// UnsafeEventStoreServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EventStoreServer will
// result in compilation errors.
type UnsafeEventStoreServer interface {
	mustEmbedUnimplementedEventStoreServer()
}

func RegisterEventStoreServer(s grpc.ServiceRegistrar, srv EventStoreServer) {
	s.RegisterService(&EventStore_ServiceDesc, srv)
}

func _EventStore_Append_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Event_AppendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventStoreServer).Append(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/flipbook.v1.EventStore/Append",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventStoreServer).Append(ctx, req.(*Event_AppendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventStore_Iterate_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(EventStoreServer).Iterate(&eventStoreIterateServer{stream})
}

type EventStore_IterateServer interface {
	Send(*Event) error
	Recv() (*Event_IterateRequest, error)
	grpc.ServerStream
}

type eventStoreIterateServer struct {
	grpc.ServerStream
}

func (x *eventStoreIterateServer) Send(m *Event) error {
	return x.ServerStream.SendMsg(m)
}

func (x *eventStoreIterateServer) Recv() (*Event_IterateRequest, error) {
	m := new(Event_IterateRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _EventStore_GetLatest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Event_GetLatestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventStoreServer).GetLatest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/flipbook.v1.EventStore/GetLatest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventStoreServer).GetLatest(ctx, req.(*Event_GetLatestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EventStore_ServiceDesc is the grpc.ServiceDesc for EventStore service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EventStore_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "flipbook.v1.EventStore",
	HandlerType: (*EventStoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Append",
			Handler:    _EventStore_Append_Handler,
		},
		{
			MethodName: "GetLatest",
			Handler:    _EventStore_GetLatest_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Iterate",
			Handler:       _EventStore_Iterate_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "api/v1/eventstore.proto",
}
