// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             (unknown)
// source: v1/snapshotstore.proto

package apiv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SnapshotStoreClient is the client API for SnapshotStore service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SnapshotStoreClient interface {
	Set(ctx context.Context, in *Snapshot, opts ...grpc.CallOption) (*emptypb.Empty, error)
	Get(ctx context.Context, in *Snapshot_GetRequest, opts ...grpc.CallOption) (*Snapshot, error)
}

type snapshotStoreClient struct {
	cc grpc.ClientConnInterface
}

func NewSnapshotStoreClient(cc grpc.ClientConnInterface) SnapshotStoreClient {
	return &snapshotStoreClient{cc}
}

func (c *snapshotStoreClient) Set(ctx context.Context, in *Snapshot, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/eventsauce.api.v1.SnapshotStore/Set", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *snapshotStoreClient) Get(ctx context.Context, in *Snapshot_GetRequest, opts ...grpc.CallOption) (*Snapshot, error) {
	out := new(Snapshot)
	err := c.cc.Invoke(ctx, "/eventsauce.api.v1.SnapshotStore/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SnapshotStoreServer is the server API for SnapshotStore service.
// All implementations must embed UnimplementedSnapshotStoreServer
// for forward compatibility
type SnapshotStoreServer interface {
	Set(context.Context, *Snapshot) (*emptypb.Empty, error)
	Get(context.Context, *Snapshot_GetRequest) (*Snapshot, error)
	mustEmbedUnimplementedSnapshotStoreServer()
}

// UnimplementedSnapshotStoreServer must be embedded to have forward compatible implementations.
type UnimplementedSnapshotStoreServer struct {
}

func (UnimplementedSnapshotStoreServer) Set(context.Context, *Snapshot) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Set not implemented")
}
func (UnimplementedSnapshotStoreServer) Get(context.Context, *Snapshot_GetRequest) (*Snapshot, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedSnapshotStoreServer) mustEmbedUnimplementedSnapshotStoreServer() {}

// UnsafeSnapshotStoreServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SnapshotStoreServer will
// result in compilation errors.
type UnsafeSnapshotStoreServer interface {
	mustEmbedUnimplementedSnapshotStoreServer()
}

func RegisterSnapshotStoreServer(s grpc.ServiceRegistrar, srv SnapshotStoreServer) {
	s.RegisterService(&SnapshotStore_ServiceDesc, srv)
}

func _SnapshotStore_Set_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Snapshot)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SnapshotStoreServer).Set(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/eventsauce.api.v1.SnapshotStore/Set",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SnapshotStoreServer).Set(ctx, req.(*Snapshot))
	}
	return interceptor(ctx, in, info, handler)
}

func _SnapshotStore_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Snapshot_GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SnapshotStoreServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/eventsauce.api.v1.SnapshotStore/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SnapshotStoreServer).Get(ctx, req.(*Snapshot_GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SnapshotStore_ServiceDesc is the grpc.ServiceDesc for SnapshotStore service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SnapshotStore_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "eventsauce.api.v1.SnapshotStore",
	HandlerType: (*SnapshotStoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Set",
			Handler:    _SnapshotStore_Set_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _SnapshotStore_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v1/snapshotstore.proto",
}
