// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package database

import (
	"github.com/google/uuid"
)

type Event struct {
	PartitionKey uuid.UUID
	SortingKey   int64
	EventPayload []byte
}
